openapi: 3.0.0
info:
  title: Tag API
  version: 1.0.0

paths:
  /api/todo/tag/createTag:
    post:
      summary: Create a tag
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, color]
              properties:
                name:
                  type: string
                color:
                  type: string
      responses:
        '200':
          description: Tag created successfully
        '400':
          description: Invalid input

  /api/todo/tag/getTagById:
    post:
      summary: Get tag by ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [id]
              properties:
                id:
                  type: integer
      responses:
        '200':
          description: Tag found
        '404':
          description: Tag not found

  /api/todo/tag/getAllTags:
    post:
      summary: Get all tags
      responses:
        '200':
          description: All tags returned

  /api/todo/tag/deleteTag:
    post:
      summary: Delete a tag
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [id]
              properties:
                id:
                  type: integer
      responses:
        '200':
          description: Tag deleted
        '404':
          description: Tag not found

  /api/todo/tag/updateTagColor:
    post:
      summary: Update tag color
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [id, color]
              properties:
                id:
                  type: integer
                color:
                  type: string
      responses:
        '200':
          description: Tag color updated
        '404':
          description: Tag not found