openapi: 3.0.0
info:
  title: Task API
  version: 1.0.0

paths:
  /api/todo/tasktag/addTagToTask:
    post:
      summary: Add a tag to a task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [task_id, tag_id]
              properties:
                task_id:
                  type: integer
                tag_id:
                  type: integer
      responses:
        '201':
          description: Tag added to task
        '400':
          description: Invalid input

  /api/todo/tasktag/removeTagFromTask:
    post:
      summary: Remove a tag from a task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [task_id, tag_id]
              properties:
                task_id:
                  type: integer
                tag_id:
                  type: integer
      responses:
        '200':
          description: Tag removed from task
        '400':
          description: Invalid input

  /api/todo/tasktag/getTagsForTask:
    post:
      summary: Get all tags for a task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [task_id]
              properties:
                task_id:
                  type: integer
      responses:
        '200':
          description: List of tags for the task
        '400':
          description: Invalid task ID